services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: libraryDb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryDB=Host=db;Port=5432;Database=libraryDb;Username=postgres;Password=1234
    depends_on:
      - db
    ports:
      - "5000:8080"
    volumes:
      - ./dumps:/app/dumps
    command: >
      sh -c "dotnet ef database update && dotnet library-RESTful.dll"

volumes:
  db-data:
