services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: libraryDb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d # Автоматическая инициализация базы
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryDB=Host=db;Port=5432;Database=libraryDb;Username=myuser;Password=mypassword
    depends_on:
      - db
    ports:
     - "5000:8080"
    volumes:
      - ./dumps:/app/dumps # Для использования дампа в приложении

volumes:
  db-data:
